console.log("Working")
/* 
-----------DURATION-----------

100 MS TO JUMP, FEELS NO LAG, FEELS NO ANIMATION, INSTANTANEOUS

1s FEELS A LITTLE LAG, LIKE ANIMATION, STILL CONNECTED

10s  DISCONNECTED, MUST ADD PLAY BUTTON ON THIS

250~300MS: SWEET SPOT FOR MANY ANIMATIONS

FASTER != BETTER



*/